language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - touch .coverage
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `login`;'
script: phpunit
env:
  - DB=mysql

before_install:
  - pip install --user codecov
after_success:
  - codecov

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always

